language: node_js
node_js:
   - "node"
after_script: "./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --require babel-core/register -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
notifications:
  email:
    recipients:
      - KSDaemon@ya.ru
    on_success: change
    on_failure: always
